"""Run with an active local server. Uses installed Edge, no browser download."""
import sys, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'.packages'))
from playwright.sync_api import sync_playwright

out=ROOT/'test-artifacts';out.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser=p.chromium.launch(channel='msedge',headless=True)
    page=browser.new_page(viewport={'width':1440,'height':1050})
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://127.0.0.1:8000')
    page.get_by_role('heading',name='Understand the fine print.').wait_for()
    page.screenshot(path=str(out/'overview-empty.png'),full_page=True)
    page.get_by_role('button',name='Explore a sample',exact=False).first.click()
    page.locator('#jurisdiction').select_option('India · Maharashtra')
    page.locator('#submit-upload').click()
    page.locator('.source-clause').first.wait_for()
    assert page.locator('.source-clause').count()==9
    page.get_by_role('button',name='Attention flags',exact=True).click()
    page.get_by_role('heading',name='Conflicting deposit return periods',exact=True).wait_for()
    page.get_by_role('button',name='Inspect source',exact=False).first.click()
    assert '45 calendar days' in page.locator('.source-clause.highlight').inner_text()
    page.get_by_role('button',name='Related passage',exact=False).first.click()
    assert '30 calendar days' in page.locator('.source-clause.highlight').inner_text()
    page.get_by_role('button',name='What if?',exact=True).click()
    page.locator('#count-rule').select_option('exclude')
    page.locator('#calculate').click()
    assert '30 November 2026' in page.locator('#scenario-result').inner_text()
    page.goto('http://127.0.0.1:8000/#compare')
    page.locator('#compare-run').click()
    page.locator('.compare-row').first.wait_for()
    assert page.locator('.compare-row').count()==4
    assert '23,000' in page.locator('#comparison-results').inner_text()
    page.screenshot(path=str(out/'comparison.png'),full_page=True)
    page.goto('http://127.0.0.1:8000/#ask')
    page.locator('#question').fill('Are pets permitted?')
    page.locator('#ask-form button').click()
    page.get_by_text('I couldn’t find this in the provided document.',exact=True).wait_for()
    page.locator('#question').fill('What happens if payment is late?')
    page.locator('#ask-form button').click()
    page.locator('#answer blockquote').first.wait_for()
    assert 'INR 500' in page.locator('#answer').inner_text()
    page.goto('http://127.0.0.1:8000/#actions')
    page.locator('#generate-tasks').click()
    page.locator('[data-edit-task]').first.wait_for()
    page.locator('[data-edit-task]').first.fill('Confirm my exact notice receipt date')
    page.locator('[data-edit-task]').first.press('Tab')
    page.get_by_text('Task edit saved.',exact=True).wait_for()
    page.reload()
    assert page.locator('[data-edit-task]').first.input_value()=='Confirm my exact notice receipt date'
    page.locator('[data-check]').first.check()
    page.get_by_text('Checklist saved for this session.',exact=True).wait_for()
    page.reload()
    assert page.locator('[data-check]').first.is_checked()
    page.goto('http://127.0.0.1:8000/#brief')
    page.locator('#objective').fill('Understand early termination costs')
    page.locator('#facts').fill('I may relocate in February.')
    page.locator('#generate-brief').click()
    page.get_by_text('Brief generated and saved for this session.',exact=True).wait_for()
    assert 'I may relocate in February.' in page.locator('#brief-text').input_value()
    page.context.grant_permissions(['clipboard-read','clipboard-write'])
    page.locator('#copy-brief').click()
    page.get_by_text('Brief copied.',exact=True).wait_for()
    assert 'I may relocate in February.' in page.evaluate('navigator.clipboard.readText()')
    with page.expect_download() as download:
        page.locator('#download-brief').click()
    download.value.save_as(str(out/'lawyer-brief.txt'))
    page.evaluate('window.print = () => { window.printInvoked = true; }')
    page.locator('#print-brief').click()
    page.wait_for_function('window.printInvoked === true')
    assert 'CONSULTATION PREPARATION BRIEF' in page.locator('.print-sheet').text_content()
    page.goto('http://127.0.0.1:8000/#overview')
    page.screenshot(path=str(out/'overview-samples.png'),full_page=True)
    page.set_viewport_size({'width':390,'height':844})
    page.screenshot(path=str(out/'mobile-overview.png'),full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.locator('#menu').click()
    page.get_by_role('link',name='Documents',exact=False).first.click()
    page.locator('[data-open]').first.click()
    page.get_by_role('button',name='Explanation & findings').click()
    assert page.locator('.analysis').is_visible()
    page.get_by_role('button',name='Original source',exact=True).click()
    assert page.locator('.source').is_visible()
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.screenshot(path=str(out/'mobile-review.png'),full_page=True)
    page.keyboard.press('Tab')
    assert page.evaluate('document.activeElement.tagName') in ['BUTTON','A','SELECT','INPUT','TEXTAREA']
    page.locator('.topbar [data-action="upload"]').click()
    page.locator('#jurisdiction').select_option('Unknown')
    page.locator('#file').set_input_files(str(ROOT/'samples'/'freelancer.txt'))
    page.locator('#submit-upload').click()
    page.get_by_role('heading',name='freelancer.txt',exact=True).first.wait_for()
    assert 'Text-based review' in page.locator('.notice').first.inner_text()
    page.goto('http://127.0.0.1:8000/#documents')
    page.on('dialog',lambda dialog:dialog.accept())
    page.locator('.doc-card').filter(has=page.get_by_role('heading',name='freelancer.txt',exact=True)).get_by_role('button',name='Delete',exact=True).click()
    page.get_by_text('Document deleted from this session.',exact=True).wait_for()
    assert page.locator('.doc-card').count()==3
    assert not errors, errors
    browser.close()
print('Browser checks passed: samples, source citations, comparison, unsupported question, payment retrieval, scenario, task persistence, brief copy/download/print, mobile layout, keyboard focus, file upload and deletion. No JavaScript errors.')
